config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "kittens#index"

  resources :kittens
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true, numericality: { only_integer: true }
  validates :cuteness, presence: true
  validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Kitten created successfully"
      redirect_to @kitten
    else
      flash.now[:error] = @kitten.errors.fullmessage
      render :new, :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(kitten_params)
      redirect_to @kitten
    else
      render :edit, :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def kitten_params
    params.require(:kitten).permit(:age, :name, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten_form.html.erb
<%= form_with model: kitten do |form| %>
    <%= form.label :name, 'Name'%>
    <%= form.text_field :name%>
    <%= form.label :age, 'Age'%>
    <%= form.text_field :age%>
    <%= form.label :cuteness, 'Cuteness'%>
    <%= form.text_field :cuteness%>
    <%= form.label :softness, 'Softness'%>
    <%= form.text_field :softness%>
    <%= form.submit 'Create'%>
<%end%>

app/views/kittens/edit.html.erb
<%= render 'kitten_form', kitten: @kitten%>

app/views/kittens/index.html.erb
<%= link_to 'Create a kitten', new_kitten_path%>
<h2>List of Kittens</h2>
<div>
    <% @kittens.each do |kitten| %>
        <div>Kitten name: <%= kitten.name%></div>
        <div>Kitten age: <%= kitten.age%></div>
        <div><%= link_to "Delete", kitten_path(kitten), data: {
                    turbo_method: :delete}%></div>
    <% end %>
    <br>
</div>

app/views/kittens/new.html.erb
<%= render 'kitten_form', kitten: @kitten%>

app/views/kittens/show.html.erb
<%= flash[:success] %>
<div><%=@kitten.name%></div>
<div><%=@kitten.age%></div>
<div><%=@kitten.cuteness%></div>
<div><%=@kitten.softness%></div>

<div><%= link_to "Edit Kitten", edit_kitten_path(@kitten) %></div>
<div><%= link_to "Delete", kitten_path(@kitten), data: {
                    turbo_method: :delete}%></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>